### ISSUE TITLE
Cannot read property...

### ISSUE THREAD

**Issue by simbo** [w0rm/gulp-postcss#14]
Hi,

i'm using gulp-postcss together with gulp-sass 1.2.4, autoprefixer-core 4.0.2, css-mqpacker 2.0.0 and csswring 2.0.0 like this:

```
gulp.task('build:css', function() {
    return gulp
        .src(config.paths.assetsDev + '/scss/main.scss')
        .pipe(g.sourcemaps.init())
        .pipe(g.sass())
        .pipe(g.postcss([
                autoprefixer(config.autoprefixer),
                mqpacker,
                csswring(config.csswring)
        ]))
        .pipe(g.sourcemaps.write('.', {
            includeContent: true,
            sourceRoot: '.'
        }))
        .pipe(gulp.dest(path.join(config.paths.assets, 'css')));
});
```

When using gulp-postcss 4.0.0 i get the following error:

```
TypeError: Cannot read property '_autoprefixerDisabled' of undefined at Processor.disabled (.../node_modules/autoprefixer-core/lib/processor.js:133:15)
```

Or if i disable autoprefixer and only use mqpacker and csswring, i get:

```
TypeError: Cannot read property 'length' of undefined at wringRule (.../node_modules/csswring/lib/csswring.js:375:18)
```

I had no problems with that when using gulp-postcss 3.0.0 and switching back "solves" the problem.

Although i'm using a lot of other modules, i assume this is a gulp-postcss problem...?!

Greetings,

Simbo

**Comment by waldemarfm** [comment]
Can confirm. Exactly the same errors with same package versions.

**Comment by w0rm** [comment]
Yeah, seems to be the right way to solve this problem. I will make this change to gulp-postcss as well so users will have more control over which version of PostCSS to use.

**Comment by ai** [comment]
@MoOx are you agree to add `peerDependencies` to all plugins? Also I add this recommendation to plugin developer How To (it is in progress right now).

**Comment by w0rm** [comment]
gulp-postcss now lists postcss in peerDependencies.

**Comment by sondr3** [comment]
Sorry to bother, but any idea when this will be finished? :)

**Comment by MoOx** [comment]
peerDep will be deprecated, so not sure it's a good idea.
https://github.com/npm/npm/issues/6565

**Comment by MoOx** [comment]
The why you should not use dep is overthere https://github.com/npm/npm/issues/5080

**Comment by w0rm** [comment]
@MoOx any suggestions on how to prevent version mismatch?

**Comment by MoOx** [comment]
Don't know any magic method. I just too many undesired issues with peerDep too.

Developers should take care of that. When someone upgrade a tool with some plugins, this person should ensure all plugins have versions that work with the new version of the tool. IMO, it's that simple.

Each plugins might specify minimal version they require in their README.

**Comment by MoOx** [comment]
Note that all the plugins I published for example have tests with a specific postcss version (cf devDep). Developers can also take a look to that. Version in README seems a good idea tho.

**Comment by ai** [comment]
Maybe we can set some special flag to plugin with PostCSS AST version they required? I do not really like this idea, only as brainstorm.

**Comment by ai** [comment]
Like:

```js
module.export = {
    postcss: function () {},
    ast: '4.0.0'
}
```

And PostCSS will throw error if plugins expect different AST versions.

**Comment by MoOx** [comment]
Maybe more

```js
module.export = {
    postcss: function () {},
    postcssVersion: require("./package.json").devDependencies.postcss
}
```
?

Note sure we should handle this in the core tho.
We all get this kind of issue with all tool/plugins things, this is not likely easy to solve.

**Comment by w0rm** [comment]
If each plugin exposed its postcss version, then postcss itself could check it with smth like  https://github.com/npm/node-semver and throw an error

**Comment by ai** [comment]
Main problems:

1. Does API check is a part of PostCSS?
2. What we will suggest to user? Downgrade plugin version?
3. I think short plugin syntax (just a function) is important on debug. Should we allow it and miss API check it this case?

**Comment by w0rm** [comment]
This suggestion seems to be the way how this should be solved https://github.com/npm/npm/issues/5080#issuecomment-40545825

**Comment by yisibl** [comment]
It is certainly a headache problem.

**Comment by MoOx** [comment]
I like the way isaac explains. So this can be handled in plugin like this:

```js
var plugin = function () {}

plugin.supportedVersion = require("./package.json").dependencies.postcss || require("./package.json").devDependencies.postcss

module.export = plugin
```

It would be could to directly add a `supportedVersion` property to the plugin itself.
This way, postcss can check for this without having to rely on a object that contains function+supported version.

What do you think guys?

Btw, this should only show a warning because for example a plugin done for v3 can totally work for v4 (the otherwise is not likely to work all the time).

**Comment by ai** [comment]
I found the best solution. We dont necessarily have to use one AST version in every plugin. If plugin uses old AST we can stringify current one and then reparse it with old PostCSS for this plugin.

Every plugin should have own PostCSS version in `dependencies` and will use special mathod to wrap plugin function:

```js
var postcss = require('postcss');

module.exports = postcss.plugin(function (css) {
    // css will be in plugin’s PostCSS version
});
```

`postcss.plugin` will be like:

```js
postcss.plugin = function (plugin) {
    return function (ast) {
        // here will be smarter semver check
        if ( ast.postcss.version == postcss.version ) {
            return plugin(ast);
        } else {
            var old    = postcss.parse( ast.toResult() );
            var result = plugin(old);
            return ast.postcss.parse( result.toResult() );
        }
    };
});
```

**Comment by MoOx** [comment]
Overkill !
We should not take care of this. It's up to the developer to know which version of the tool he use, & so which version of plugin to use too.

Your solution might create slow result if several postcss plugins use severals versions of postcss.
Sound like over-engineering to me.

We don't have to handle this kind of issue...

**Comment by ai** [comment]
@MoOx but slow plugin is better, that broken plugin :)

**Comment by MoOx** [comment]
Also, you will have to face a new problem cause a new version might parse something a previous version fails to. You don't want user to want an report issue about that.

Plugin is not broken, just no compatible (yet?).

**Comment by kristoferjoseph** [comment]
Sooo, 
What steps does one need to take to get the documented example in the README to work without error? 
Thanks :)

**Comment by ai** [comment]
Autoprefixer 5.0 was released with PostCSS 4.0 support. Please update.

**Comment by w0rm** [comment]
@MoOx @ai should I revert commit that made postcss into peerDepency or is it fine for gulp plugin?

**Comment by w0rm** [comment]
@kristoferjoseph PR for the README is very welcome!

**Comment by ai** [comment]
@w0rm I am not so familiar with npm :(. @MoOx knows better.

**Comment by MoOx** [comment]
Note: I don't use gulp anymore so I don't care =)

Since npm plan to deprecate this feature, I think you should not use this.
And it brings the exact same kind of issue as normal dep: https://github.com/webpack/webpack/issues/570#issuecomment-65760396

**Comment by TrySound** [comment]
If somebody needs old plugin let use old versions of other plugins and postcss.

**Comment by w0rm** [comment]
@MoOx so webpack loaders are the new hype thing =) 

@TrySound to use with previous version of postcss simply pick corresponding version of gulp-postcss from the change log.

**Comment by TrySound** [comment]
Yes, I am about it.

**Comment by MoOx** [comment]
(@worm my build process is more based on npm itself (npm scripts) than on webpack. Check it out https://github.com/MoOx/frontend-hot-starterkit)

Maybe we should close this issue for now (and encourage people to read CHANGELOG & README & package.json).

**Comment by MoOx** [comment]
Maybe an issue should be created to postcss directly.

**Comment by ai** [comment]
There is right now https://github.com/postcss/postcss/issues/163

**Comment by MoOx** [comment]
Perfect.

**Comment by w0rm** [comment]
Put PostCSS back into simple dependency and republished on npm ([commit](https://github.com/w0rm/gulp-postcss/commit/6bc9e3702a80229070f0201af89e1ab383518c00))

**Comment by ai** [comment]
Next PostCSS 4.1 will print warning if plugin throwed a error and was based on different PostCSS version: https://github.com/postcss/postcss/commit/3d48436b003fc081bc9e0694d8add0db5d65834d

**Comment by sidoruk-sv** [comment]
The same issues can occur when you make a mistake in an array of processors and undefined item appear in a row:
`[processor1,, processor2]`
