### ISSUE TITLE
problem with package.json

### ISSUE THREAD

**Issue by lexich** [w0rm/gulp-postcss#16]
```bash
> npm install gulp-postcss@4.0.1

npm ERR! Darwin 14.0.0
npm ERR! argv "node" "/Users/lexich/.nvm/v0.10.35/bin/npm" "install" "gulp-postcss@4.0.1"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package postcss does not satisfy its siblings' peerDependencies requirements!
```

i think that problem is here
https://github.com/w0rm/gulp-postcss/blob/master/package.json#L30
https://github.com/w0rm/gulp-postcss/blob/master/package.json#L30

```"postcss": "4.*",``` 4.* isn't valid version

**Comment by w0rm** [comment]
@lexich what postcss version do you have in your package.json? I changed gulp-postcss postcss to peerDependency because of #14 but turns out it was a bad idea and I will revert it back.

**Comment by lexich** [comment]
@w0rm At this monent I use old version gulp-postcss: "^3.0.7" and can't install "^4.0.0", "^4.0.1" because npm doesn't like package.json of gulp-postcss. I think you need to use something like this: ```"postcss": "~4.0.1"``` according semver

**Comment by w0rm** [comment]
@lexich it complained about mismatched peerDependency, that's why I am asking what postcss version did you have prior to installing gulp-postcss@4.0.1, if you have postcss 3.0 or less then you will get this error.

**Comment by lexich** [comment]
Yes, you a right, I also have postcss 3.0. Thank you for help.
