### ISSUE TITLE
Gulp crash

### ISSUE THREAD

**Issue by TrySound** [w0rm/gulp-postcss#17]
On syntax error like
```
// Unhandled stream error in pipe.
CssSyntaxError: path.css:15:1: Unclosed block
```
Have to use gulp-plumber for this.

Can you do some improvements to fix this?

**Comment by w0rm** [comment]
Try `.pipe(postcss(processors).on('error', gutil.log))` in your code, it seems to be the correct way of logging stream errors.

**Comment by w0rm** [comment]
I found this doc that explains error handling https://gist.github.com/floatdrop/8269868

**Comment by TrySound** [comment]
I know plumber works fine. I just think plugin have to handle errors correctly.

**Comment by w0rm** [comment]
Emitting stream errors is the correct way of handling errors. 
See it as an api that allows developers to decide what to do with the error.
Please find [p.6 in gulp plugin guidlines](https://github.com/gulpjs/gulp/blob/master/docs/writing-a-plugin/guidelines.md)
