### ISSUE TITLE
Support runner guidelines

### ISSUE THREAD

**Issue by w0rm** [w0rm/gulp-postcss#21]
[PostCSS Runner Guidelines
](https://github.com/postcss/postcss/blob/master/Runner%20Guidelines.md)

**Comment by ai** [comment]
Don’t forget to uses warnings API

**Comment by w0rm** [comment]
Yeah, I'm now trying several approaches of how this may be tested, I don't like the current one and I think of a better approach to mock postcss module completely in order to spy on the passed options.

**Comment by w0rm** [comment]
@ai I took a look into postcss-log-warnings and postcss-messages plugins, and I think its better to just use them instead of integrating this into gulp-postcss, what do you think?

**Comment by ai** [comment]
Yeap, I think so. But does Gulp Guidelines allow it? As I understand you must to write `gulp-postcss` and uses common syntax.

**Comment by w0rm** [comment]
There is gulp-utils package that has log method, I decided to use it to output warnings. I'm not sure about the formatting, I simply joined warnings with new line symbol for now.

**Comment by ai** [comment]
@w0rm it is fine for now. `postcss-messages` works same.

**Comment by w0rm** [comment]
@ai ok, I will publish a new version that follows runner guidelines

**Comment by ai** [comment]
Awesome. Ping me when you finish it. I post a trolling tweet that Gulp is better :-)

**Comment by w0rm** [comment]
@ai 5.1.0 published on npm

**Comment by ai** [comment]
Holywar tweet was sent :D

**Comment by w0rm** [comment]
@ai cool, thanks for the mention!
