### ISSUE TITLE
Add Promise polyfill

### ISSUE THREAD

**Issue by ai** [w0rm/gulp-postcss#25]
A saw, that many uses complaint about Promises. For example, we had issue here: https://github.com/yeoman/generator-gulp-webapp/pull/298#issuecomment-89821413

I think gulp-postcss must have polyfill to make users happy out of box.

/cc @w0rm

**Comment by w0rm** [comment]
What about doing it in postcss itself, you could have something like this `var Promise = global.Promise || require('promise')

**Comment by ai** [comment]
I afraid that browsers standalone build become too big.

**Comment by w0rm** [comment]
What is the size of the smallest A+ promise implementation?

**Comment by w0rm** [comment]
Answering my question: https://github.com/jakearchibald/es6-promise minified and gzipped is ~2.2k gzipped

**Comment by ai** [comment]
Problem is that it is even not necessary for most browsers. But maybe I can ask standalone build to ignore Promise polyfill.

**Comment by ai** [comment]
@w0rm all PostCSS is about 20 KB, so 10% extra size in sensible ;)

**Comment by w0rm** [comment]
Its not extra, it is required to work in some environments. And I generally don't like the idea of having to change the environment itself in order for postcss to work.

**Comment by w0rm** [comment]
Can I at least pass Promise in options instead of changing the globals?

**Comment by ai** [comment]
Hm. Yeap, gulp-postcss must change global :(. OK, I will release version with polyfill.

**Comment by ai** [comment]
PostCSS 4.1.3 now contains Promise polyfill. You can remove notice from README.md.
