### ISSUE TITLE
error setting from and to options

### ISSUE THREAD

**Issue by tinchoz49** [w0rm/gulp-postcss#30]
Hi!!

I think that 

```
opts.from = opts.to = file.path
```

Is not ok.. opts.to must be the path of the "gulp.dest" . What do you think?

**Comment by tinchoz49** [comment]
but since it's imposible knows that (the destination of the final stream)  maybe is better if we can set the option "to" manually.

```javascript
gulp.src('./src/*.css')
    .pipe(postcss(processors,{
        to: './dest/index.css'
    }))
    .pipe(gulp.dest('./dest'));
```

**Comment by w0rm** [comment]
Hi! What is the error that you get?

**Comment by w0rm** [comment]
@tinchoz49 sorry for the short reply! Can you tell more about your use case, why do you need to set `to` option? gulp is supposed to change file object in place—so during the transformation, both source and destination should be the same.

**Comment by tinchoz49** [comment]
Hi w0rm! don't worry for the short reply :)

I understand why are you setting both. 
The problem is when i'm using postcss-url, because the option "to" must be the final destination to rebase correctly the urls in the css. But is ok, I think that i preffer create a custom function to that and keep gulp-postcss respecting the runner guidelines :+1: 

close this issue if you are aggree. Thanks!!

**Comment by w0rm** [comment]
Let's keep this open, maybe @ai can offer a good solution for this?

**Comment by tinchoz49** [comment]
ok, great! maybe a solution is replace the line 37: 

```javascript
opts.from = opts.to = file.path
```

for 

```javascript
opts.from = file.path

if ( !(opts.to) ) {
  opts.to = opts.from
}
```

**Comment by ai** [comment]
Yeap, @tinchoz49 way looks nice

**Comment by w0rm** [comment]
Ok I will publish a fix for this tonight.

**Comment by w0rm** [comment]
@ai I wonder about any possibility of it might screw the source maps generation.

**Comment by ai** [comment]
@w0rm anyway gulp use other module to generate source map :)

**Comment by ai** [comment]
@tinchoz49 suggest is nice, because maybe somebody will want to override `opts.to`. But there is no need to set `opts.to` mandatory in long and unusable way. `opt.to = opt.from` is a better solution, that unusable API
